#!/usr/bin/env sh

TOOLCHAIN=$1

cmake .. -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DUA_ENABLE_ENCRYPTION=MBEDTLS -DUA_ENABLE_PUBSUB=ON -DUA_ENABLE_AMALGAMATION=ON -DCMAKE_TOOLCHAIN_FILE=./tools/cmake/$TOOLCHAIN

