#!/usr/bin/env sh

# cmake .. -DUA_ENABLE_ENCRYPTION=ON -DUA_ENABLE_PUBSUB=ON -DUA_BUILD_EXAMPLES=ON
cmake .. -DUA_ENABLE_ENCRYPTION=OPENSSL \
	-DUA_ENABLE_SUBSCRIPTIONS_EVENTS=ON \
	-DUA_ENABLE_JSON_ENCODING=ON \
	-DUA_ENABLE_PUBSUB=ON \
	-DUA_BUILD_EXAMPLES=ON \
	-DUA_ENABLE_MQTT=ON \
	-DUA_ENABLE_PUBSUB_INFORMATIONMODEL=ON \

