#!/usr/bin/env sh

cmake .. -DUA_ENABLE_ENCRYPTION=ON -DUA_ENABLE_PUBSUB=ON -DUA_ENABLE_AMALGAMATION=ON -DUA_LOGLEVEL=0
# cmake .. -DUA_ENABLE_ENCRYPTION=ON -DUA_ENABLE_PUBSUB=ON -DUA_ENABLE_AMALGAMATION=ON

