#!/usr/bin/env sh

cmake .. -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DUA_ENABLE_ENCRYPTION=OPENSSL -DUA_ENABLE_PUBSUB=ON -DUA_ENABLE_AMALGAMATION=ON -DBUILD_SHARED_LIBS=OFF
# cmake .. -DUA_ENABLE_ENCRYPTION=ON -DUA_ENABLE_PUBSUB=ON -DUA_ENABLE_AMALGAMATION=ON -DUA_LOGLEVEL=0
# cmake .. -DUA_ENABLE_ENCRYPTION=ON -DUA_ENABLE_PUBSUB=ON -DUA_ENABLE_AMALGAMATION=ON

