
#include "open62541.h"
#include "luaaa.hpp"

/****
 * opcua enums
 * @module opcua.enums
 */

namespace lua_opcua {

void reg_opcua_enums(lua_State *L) {
	/***
	 * UA_ClientState enum
	 * @table UA_ClientState
	 */
	/*
	module.new_enum("UA_ClientState",
		"DISCONNECTED", UA_ClientState::UA_CLIENTSTATE_DISCONNECTED, /// @field DISCONNECTED Disconnected
		"CONNECTED", UA_ClientState::UA_CLIENTSTATE_CONNECTED, /// @field CONNECTED Connected
		"SECURECHANNEL", UA_ClientState::UA_CLIENTSTATE_SECURECHANNEL, /// @field SECURECHANNEL Secure channel
		"SESSION", UA_ClientState::UA_CLIENTSTATE_SESSION, /// @filed SESSION - UA_CLIENTSTATE_SESSION
		"SESSION_RENEWED", UA_ClientState::UA_CLIENTSTATE_SESSION_RENEWED /// @field SESSION_RENEWED - UA_CLIENTSTATE_SESSION_RENEWED
	);
	*/
	LuaModule cState(L, "UA_ConnectionState");
	cState.def("CLOSED",		UA_CONNECTIONSTATE_CLOSED);
	cState.def("OPENING",		UA_CONNECTIONSTATE_OPENING);
	cState.def("ESTABLISHED",	UA_CONNECTIONSTATE_ESTABLISHED);
	cState.def("CLOSING",		UA_CONNECTIONSTATE_CLOSING);

	LuaModule scState(L, "UA_SecureChannelState");
	scState("CLOSED",		UA_SecureChannelState::UA_SECURECHANNELSTATE_CLOSED);
	scState("HEL_SENT",		UA_SecureChannelState::UA_SECURECHANNELSTATE_HEL_SENT);
	scState("HEL_RECEIVED",	UA_SecureChannelState::UA_SECURECHANNELSTATE_HEL_RECEIVED);
	scState("ACK_SENT",		UA_SecureChannelState::UA_SECURECHANNELSTATE_ACK_SENT);
	scState("ACK_RECEIVED",	UA_SecureChannelState::UA_SECURECHANNELSTATE_ACK_RECEIVED);
	scState("OPEN_SENT",	UA_SecureChannelState::UA_SECURECHANNELSTATE_OPN_SENT);
	scState("OPEN",			UA_SecureChannelState::UA_SECURECHANNELSTATE_OPEN);
	scState("CLOSING",		UA_SecureChannelState::UA_SECURECHANNELSTATE_CLOSING);

	LuaModule sState(L, "UA_SessionState");
	sState("CLOSED",			UA_SessionState::UA_SESSIONSTATE_CLOSED);
	sState("REQUESTED",			UA_SessionState::UA_SESSIONSTATE_CREATE_REQUESTED);
	sState("CREATED",			UA_SessionState::UA_SESSIONSTATE_CREATED);
	sState("ACTIVTE_REQUESTED",	UA_SessionState::UA_SESSIONSTATE_ACTIVATE_REQUESTED);
	sState("ACTIVATED",			UA_SessionState::UA_SESSIONSTATE_ACTIVATED);
	sState("CLOSING",			UA_SessionState::UA_SESSIONSTATE_CLOSING);

	LuaModule msMode(L, "UA_MessageSecurityMode");
	msMode("UA_MESSAGESECURITYMODE_INVALID",		UA_MessageSecurityMode::UA_MESSAGESECURITYMODE_INVALID);
	msMode("UA_MESSAGESECURITYMODE_NONE",			UA_MessageSecurityMode::UA_MESSAGESECURITYMODE_NONE);
	msMode("UA_MESSAGESECURITYMODE_SIGN",			UA_MessageSecurityMode::UA_MESSAGESECURITYMODE_SIGN);
	msMode("UA_MESSAGESECURITYMODE_SIGNANDENCRYPT", UA_MessageSecurityMode::UA_MESSAGESECURITYMODE_SIGNANDENCRYPT);

	LuaModule vType(L, "VariantType");
	vType("BOOLEAN", UA_TYPES_BOOLEAN);
	vType("SBYTE", UA_TYPES_SBYTE);
	vType("BYTE", UA_TYPES_BYTE);
	vType("INT16", UA_TYPES_INT16);
	vType("UINT16", UA_TYPES_UINT16);
	vType("INT32", UA_TYPES_INT32);
	vType("UINT32", UA_TYPES_UINT32);
	vType("INT64", UA_TYPES_INT64);
	vType("UINT64", UA_TYPES_UINT64);
	vType("FLOAT", UA_TYPES_FLOAT);
	vType("DOUBLE", UA_TYPES_DOUBLE);
	vType("STRING", UA_TYPES_STRING);
	vType("DATETIME", UA_TYPES_DATETIME);
	vType("GUID", UA_TYPES_GUID);
	vType("BYTESTRING", UA_TYPES_BYTESTRING);
	vType("XMLELEMENT", UA_TYPES_XMLELEMENT);
	vType("NODEID", UA_TYPES_NODEID);
	vType("EXPANDEDNODEID", UA_TYPES_EXPANDEDNODEID);
	vType("STATUSCODE", UA_TYPES_STATUSCODE);
	vType("QUALIFIEDNAME", UA_TYPES_QUALIFIEDNAME);
	vType("LOCALIZEDTEXT", UA_TYPES_LOCALIZEDTEXT);
	vType("EXTENSIONOBJECT", UA_TYPES_EXTENSIONOBJECT);
	vType("DATAVALUE", UA_TYPES_DATAVALUE);
	vType("VARIANT", UA_TYPES_VARIANT);
	vType("DIAGNOSTICINFO", UA_TYPES_DIAGNOSTICINFO);

	LuaModule aLevel(L, "AccessLevel");
	aLevel("READ", UA_ACCESSLEVELMASK_READ);
	aLevel("WRITE", UA_ACCESSLEVELMASK_WRITE);
	aLevel("HISTORYREAD", UA_ACCESSLEVELMASK_HISTORYREAD);
	aLevel("HISTORYWRITE", UA_ACCESSLEVELMASK_HISTORYWRITE);
	aLevel("SEMANTICCHANGE", UA_ACCESSLEVELMASK_SEMANTICCHANGE);
	aLevel("STATUSWRITE", UA_ACCESSLEVELMASK_STATUSWRITE);
	aLevel("TIMESTAMPWRITE", UA_ACCESSLEVELMASK_TIMESTAMPWRITE);
	aLevel("RW", UA_ACCESSLEVELMASK_READ | UA_ACCESSLEVELMASK_WRITE);
	aLevel("ALL", 0xF);

	LuaModule wMask("WriteMask");
	wMask("ACCESSLEVEL", UA_WRITEMASK_ACCESSLEVEL);
	wMask("ARRAYDIMENSIONS", UA_WRITEMASK_ARRRAYDIMENSIONS);
	wMask("BROWSENAME", UA_WRITEMASK_BROWSENAME);
	wMask("CONTAINSNOLOOPS", UA_WRITEMASK_CONTAINSNOLOOPS);
	wMask("DATATYPE", UA_WRITEMASK_DATATYPE);
	wMask("DESCRIPTION", UA_WRITEMASK_DESCRIPTION);
	wMask("DISPLAYNAME", UA_WRITEMASK_DISPLAYNAME);
	wMask("EVENTNOTIFIER", UA_WRITEMASK_EVENTNOTIFIER);
	wMask("EXECUTABLE", UA_WRITEMASK_EXECUTABLE);
	wMask("HISTORIZING", UA_WRITEMASK_HISTORIZING);
	wMask("INVERSENAME", UA_WRITEMASK_INVERSENAME);
	wMask("ISABSTRACT", UA_WRITEMASK_ISABSTRACT);
	wMask("MINIMUMSAMPLINGINTERVAL", UA_WRITEMASK_MINIMUMSAMPLINGINTERVAL);
	wMask("NODECLASS", UA_WRITEMASK_NODECLASS);
	wMask("NODEID", UA_WRITEMASK_NODEID);
	wMask("SYMMETRIC", UA_WRITEMASK_SYMMETRIC);
	wMask("USERACCESSLEVEL", UA_WRITEMASK_USERACCESSLEVEL);
	wMask("USEREXECUTABLE", UA_WRITEMASK_USEREXECUTABLE);
	wMask("USERWRITEMASK", UA_WRITEMASK_USERWRITEMASK);
	wMask("VALUERANK", UA_WRITEMASK_VALUERANK);
	wMask("WRITEMASK", UA_WRITEMASK_WRITEMASK);
	wMask("VALUEFORVARIABLETYPE", UA_WRITEMASK_VALUEFORVARIABLETYPE);
	wMask("ALL", 0xFF);

	LuaModule vRank("ValueRank");
	vRank("SCALAR_OR_ONE_DIMENSION", UA_VALUERANK_SCALAR_OR_ONE_DIMENSION);
	vRank("ANY", UA_VALUERANK_ANY);
	vRank("SCALAR", UA_VALUERANK_SCALAR);
	vRank("ONE_OR_MORE_DIMENSIONS", UA_VALUERANK_ONE_OR_MORE_DIMENSIONS);
	vRank("ONE_DIMENSION", UA_VALUERANK_ONE_DIMENSION);
	vRank("TWO_DIMENSIONS", UA_VALUERANK_TWO_DIMENSIONS);
	vRank("THREE_DIMENSIONS", UA_VALUERANK_THREE_DIMENSIONS);

	LuaModule logLevel("LogLevel");
	logLevel("TRACE", UA_LogLevel::UA_LOGLEVEL_TRACE);
	logLevel("DEBUG", UA_LogLevel::UA_LOGLEVEL_DEBUG);
	logLevel("INFO", UA_LogLevel::UA_LOGLEVEL_INFO);
	logLevel("WARNING", UA_LogLevel::UA_LOGLEVEL_WARNING);
	logLevel("ERROR", UA_LogLevel::UA_LOGLEVEL_ERROR);
	logLevel("FATAL", UA_LogLevel::UA_LOGLEVEL_FATAL);

	LuaModule logCate("LogCategory");
	logCate("NETWORK", UA_LogCategory::UA_LOGCATEGORY_NETWORK);
	logCate("SECURECHANNEL", UA_LogCategory::UA_LOGCATEGORY_SECURECHANNEL);
	logCate("SESSION", UA_LogCategory::UA_LOGCATEGORY_SESSION);
	logCate("SERVER", UA_LogCategory::UA_LOGCATEGORY_SERVER);
	logCate("CLIENT", UA_LogCategory::UA_LOGCATEGORY_CLIENT);
	logCate("USERLAND", UA_LogCategory::UA_LOGCATEGORY_USERLAND);
	logCate("SECURITYPOLICY", UA_LogCategory::UA_LOGCATEGORY_SECURITYPOLICY);
}

}
